name: grass
channels:
  - pyg
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.14
  - pip=24.2
  - pytorch-cuda=12.1
  - pytorch==2.2.2
  - torchaudio==2.2.2
  - torchvision==0.17.2
  - pyg=2.5.2=py310_torch_2.2.0_cu121
  - pip:
      - fairscale==0.4.13
      - lion-pytorch==0.2.2
      - ogb==1.3.6
      - torchmetrics==1.4.1
